### ISSUE TITLE
pytest-pycodestyle vs pytest-codestyle?

### ISSUE THREAD

**Issue by ma-sadeghi** [henry0312/pytest-pycodestyle#86]
I'm a bit confused about `pytest-pycodestyle` and `pytest-codestyle`. I know they're two different repos, but the conda-forge feedstock for `pytest-codestyle` lists this repo as its homepage (see https://github.com/conda-forge/pytest-codestyle-feedstock#about-pytest-codestyle).

**Comment by henry0312** [comment]
Because of some historical reasons, I had maintained both `pytest-codestyle` and `pytest-pycodestyle` until v2.0.x
`pytest-codestyle` was the same with `pytest-pycodestyle`.
Please also see:

- https://github.com/henry0312/pytest-pycodestyle/releases
  - https://pypi.org/project/pytest-codestyle/
    - https://github.com/henry0312/pytest-pycodestyle/tree/end_of_support_pytest_codestyle
  - https://pypi.org/project/pytest-pycodestyle/

Today, I have maintained just `pytest-pycodestyle` since v2.1.x.

**Comment by ma-sadeghi** [comment]
Anyway, I added `pytest-pycodestyle` to conda-forge as we depend on it in two of our packages.
https://anaconda.org/conda-forge/pytest-pycodestyle
